### Test Get all Notes
GET http://localhost:3000/

### Test get note by id 
GET http://localhost:3000/nota_3d265a18bd07bba9

### Test Create Note
POST http://localhost:3000/
content-type: application/json

{
  "title": "GGG",
  "body": "GGG"
}


### Test Update a note
PUT http://localhost:3000/nota_3d265a18bd07bba9 HTTP/1.1
content-type: application/json

{
  "userId": "user-250",
  "title": "G Na",
  "body": ""
}


### Test Delete a note
DELETE http://localhost:3000/nota_3d265a18bd07bba9


### Test 404
GET http://localhost:3000/api/test



### Test Railway deployment

GET nota-server-production.up.railway.app


####
POST nota-server-production.up.railway.app
content-type: application/json

{
  "userId": "user-200",
  "title": "My first note",
  "body": "hello, guys!"
}
