### Test Get all Notes
GET http://localhost:3000/

### Test get note by id 
GET http://localhost:3000/nota_8fc118f53557eca7

### Test Create Note
POST http://localhost:3000/
content-type: application/json

{
  "userId": "user-502",
  "title": "My first note",
  "body": "hello, guys"
}


### Test Update a note
PUT http://localhost:3000/nota_8fc118f53557eca7 HTTP/1.1
content-type: application/json

{
  "userId": "user-500",
  "title": "My first note",
  "body": "hello, guys again"
}


### Test Delete a note
DELETE http://localhost:3000/nota_54e8ab60a9d009c09896fbf8de09185ef6035116c2a32e09d996fea63a699d83



### Test Railway deployment

GET http://nota-server-production.up.railway.app:3000/nota_8fc118f53557eca7


####
POST http://nota-server-production.up.railway.app:3000
content-type: application/json

{
  "userId": "user-502",
  "title": "My first note",
  "body": "hello, guys"
}
